# vim上からGitコマンドを実行できる
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  " grep検索の実行後にQuickFix Listを表示する
  autocmd QuickFixCmdPost *grep* cwindow
  
  command Gst :Gstatus
  command Gdf :Gdiff
  command Gbl :Gblame
'''